### PR TITLE
Add meshtastic color style links to 'tips' form

### PR DESCRIPTION
**Pull request by fsgl1tch**
Update the link color to match the overall green style

Old
old

New
new

### CODE REVIEW

**Comment by mkinney** [comment]
Looks great!

**Comment by thebentern** [comment]
Thanks for the PR. Looks much better. 
Can we use setStyleSheet with "a {color: #67EA94 }" instead of inline styles though? That way it shows up consistently on all instances?

**Comment by fsgl1tch** [comment]
@thebentern okey, would it be in some of the python file or the style .xml ?

**Comment by mkinney** [comment]
I'm not sure. There is a meshtastic_theme.xml in the repo. If possible to use that, it would be best.

We have also changed some of the styling in the tabs https://github.com/meshtastic/Meshtastic-gui-installer/blob/master/meshtastic_flasher/settings.py#L44

**Comment by fsgl1tch** [comment]
I will have a closer look, but should the link style be the same through out the application? I assume if I add it just in the form file with style sheet it will only affect that part.

**Comment by thebentern** [comment]
We might be able to add the stylesheet to a Qt element higher up in the structure. I believe there is some level of style inheritance within Qt applications.

**Pull request merged**
