### PR TITLE
Add advanced options as a button next to device settings

### PR DESCRIPTION
**Pull request by fsgl1tch**
form

### CODE REVIEW

**Comment by mkinney** [comment]
What would it look like if the settings and advanced options were moved to the top left (on same line as the help/info)?

**Comment by fsgl1tch** [comment]
I could try it out

**Comment by mkinney** [comment]
There's a makefile entry for "mac". Since you're on windows, you could copy the mac target to a new win target (change the ":" to ";". Once you have that, you can run "make win". It would create a single executable in dist dir. You can run that to verify the icons are all there. (completely optional)

**Comment by fsgl1tch** [comment]
Options 2
pilt
Kind of like this more :D

**Comment by mkinney** [comment]
I merged this PR thinking the 2nd option was there. Oops.

Can you create a new PR for the advanced options in the top like the picture?

**Comment by fsgl1tch** [comment]
@mkinney yes, done. I think we miss communicated, I created a possible layout

**Pull request merged**
